services:
  db:
    image: fragamemnonzor/my-mariadb-image:latest
    networks:
      - app-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=myapp
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    configs:
      - source: db_setup
        target: /docker-entrypoint-initdb.d/db_setup.sql

  web:
    image: fragamemnonzor/my-php-apache-image:latest
    networks:
      - app-net
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WEBROOT_LOCATION=${WEBROOT_LOCATION}

networks:
  app-net:
    driver: overlay
    attachable: true

configs:
  db_setup:
    file: ./db/db_setup.sql
